import { Theme } from './themeTypes';

export const BUILT_IN_THEMES: Record<string, Theme> = {
  dark: {
    name: 'dark',
    displayName: 'Dark Mode',
    colors: {
      bg: '#0f172a',
      bgSecondary: '#1e293b',
      bgTertiary: '#334155',
      text: '#f1f5f9',
      textSecondary: '#cbd5e1',
      textMuted: '#64748b',
      primary: '#3b82f6',
      primaryHover: '#2563eb',
      border: '#475569',
      messageBubbleOwn: '#3b82f6',
      messageBubbleOther: '#1e293b',
      hover: '#334155',
      accent: '#8b5cf6',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
    },
    fonts: {
      body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      mono: '"Fira Code", "Cascadia Code", "Source Code Pro", Menlo, Monaco, Consolas, monospace',
    },
    spacing: {
      roomItemPadding: '0.75rem',
      roomItemGap: '0.75rem',
      sidebarPadding: '1rem',
      messagePadding: '1rem 1.5rem',
      messageGap: '1rem',
      inputPadding: '1rem',
    },
    sizing: {
      textBase: '0.875rem',
      textSm: '0.75rem',
      textXs: '0.625rem',
      textLg: '1rem',
      textXl: '1.25rem',
      roomItemHeight: 'auto',
      avatarSize: '2.5rem',
      avatarSizeSmall: '2rem',
      borderRadius: '0.5rem',
    },
    style: {
      showRoomPrefix: false,
      roomPrefix: '',
      messageStyle: 'bubbles',
      compactMode: false,
    },
  },
  terminal: {
    name: 'terminal',
    displayName: 'Unix Terminal',
    colors: {
      bg: '#000000',
      bgSecondary: '#0a0a0a',
      bgTertiary: '#1a1a1a',
      text: '#00ff00',
      textSecondary: '#00cc00',
      textMuted: '#008800',
      primary: '#00ff00',
      primaryHover: '#00cc00',
      border: '#003300',
      messageBubbleOwn: '#003300',
      messageBubbleOther: '#001a00',
      hover: '#001100',
      accent: '#00ffff',
      success: '#00ff00',
      error: '#ff0000',
      warning: '#ffff00',
    },
    fonts: {
      body: '"IBM Plex Mono", "Courier New", Courier, monospace',
      mono: '"IBM Plex Mono", "Courier New", Courier, monospace',
    },
    spacing: {
      roomItemPadding: '0.25rem 0.5rem',
      roomItemGap: '0.25rem',
      sidebarPadding: '0.5rem',
      messagePadding: '0.25rem 0.5rem',
      messageGap: '0.125rem',
      inputPadding: '0.5rem',
    },
    sizing: {
      textBase: '0.75rem',
      textSm: '0.6875rem',
      textXs: '0.625rem',
      textLg: '0.8125rem',
      textXl: '0.875rem',
      roomItemHeight: 'auto',
      avatarSize: '1.25rem',
      avatarSizeSmall: '1rem',
      borderRadius: '0',
    },
    style: {
      showRoomPrefix: true,
      roomPrefix: '$ cd ',
      messageStyle: 'terminal',
      compactMode: true,
    },
  },
};



